spring:
  application:
    name: forum-servicev2
  
  datasource:
    url: jdbc:postgresql://localhost:5432/forumdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: always

server:
  port: 8080
